version: 1.0.{build}
environment:
  TEST_ASSEMBLIES: Tests.Unit.Presentation.Web\bin\Debug\Tests.Unit.Presentation.Web.dll
  COVERAGE_FILTER_CORE_APPLICATIONSERVICES: +[Core.ApplicationServices]*
  COVERAGE_FILTER_CORE_DOMAINMODEL: +[Core.DomainModel]*
  COVERAGE_FILTER_CORE_DOMAINSERVICES: +[Core.DomainServices]*
  COVERAGE_FILTER_INFRASTRUCTURE_DATAACCESS: +[Infrastructure.DataAccess]*
  COVERAGE_FILTER_INFRASTRUCTURE_OPENXML: +[Infrastructure.OpenXML]*
  COVERAGE_FILTER_PRESENTATION_WEB: +[Presentation.Web]*
  COVERAGE_EXCL_FILTER_PRESENTATION_WEB: -[Presentation.Web]Presentation.Web.App_Start* -[Presentation.Web]Presentation.Web.AuthConfig -[Presentation.Web]Presentation.Web.BundleConfig -[Presentation.Web]Presentation.Web.DropdownProfile -[Presentation.Web]Presentation.Web.FilterConfig -[Presentation.Web]Presentation.Web.Infrastructure.NinjectDependencyResolver -[Presentation.Web]Presentation.Web.Infrastructure.NinjectDependencyScope -[Presentation.Web]Presentation.Web.Infrastructure.UserRepositoryFactory -[Presentation.Web]Presentation.Web.Infrastructure.ProviderInitializationHttpModule -[Presentation.Web]Presentation.Web.MappingProfile -[Presentation.Web]Presentation.Web.MappingConfig -[Presentation.Web]Presentation.Web.Models* -[Presentation.Web]Presentation.Web.MvcApplication -[Presentation.Web]Presentation.Web.Properties.Settings -[Presentation.Web]Presentation.Web.RouteConfig -[Presentation.Web]Presentation.Web.Startup -[Presentation.Web]Presentation.Web.WebApiConfig
  ESLINT_DIR: Presentation.Web\Scripts\app
  TSLINT_DIR: Presentation.Web\Scripts\app
  NODEJS_VERSION: "4"
install:
  - ps: install-Product node $env:NODEJS_VERSION
  - npm install
  - node_modules\.bin\webdriver-manager update --standalone
cache:
  - node_modules -> package.json # cache node packages if package.json is the same
  - packages -> **\packages.config
before_build:
- nuget restore %APPVEYOR_BUILD_FOLDER%\KITOS.sln -verbosity quiet
build:
  project: KITOS.sln
  verbosity: minimal
  publish_wap: true
after_build:
  # - node_modules\.bin\gulp lint
test_script:
  # Use karma for local coverage report and karmaPost for coveralls.io.
  - node_modules\.bin\gulp karmaPost
  # - run-coverage.bat
  # Comment out to remove coverage from Coveralls.io
  # - post-coverage.bat
# artifacts:
# # Coverage
# - path: coverage
  # name: Backend Coverage Report
# - path: karmaCoverage
  # name: Frontend Coverage Report
# - path: results.xml
  # name: OpenCover results
deploy:
  provider: WebDeploy
  server: http://localhost/
  website: Kitos
  username: Kitos
  password:
  ntlm: false
  remove_files: true
  artifact: web-deploy-package
after_deploy:
  - node_modules\.bin\gulp protractor