version: 2.0.{build}
environment:
  TEST_ASSEMBLIES: Tests.Unit.Presentation.Web\bin\Debug\Tests.Unit.Presentation.Web.dll
  COVERAGE_FILTER_CORE_APPLICATIONSERVICES: +[Core.ApplicationServices]*
  COVERAGE_FILTER_CORE_DOMAINMODEL: +[Core.DomainModel]*
  COVERAGE_FILTER_CORE_DOMAINSERVICES: +[Core.DomainServices]*
  COVERAGE_FILTER_INFRASTRUCTURE_DATAACCESS: +[Infrastructure.DataAccess]*
  COVERAGE_FILTER_INFRASTRUCTURE_OPENXML: +[Infrastructure.OpenXML]*
  COVERAGE_FILTER_PRESENTATION_WEB: +[Presentation.Web]*
  COVERAGE_EXCL_FILTER_PRESENTATION_WEB: -[Presentation.Web]Presentation.Web.App_Start* -[Presentation.Web]Presentation.Web.AuthConfig -[Presentation.Web]Presentation.Web.BundleConfig -[Presentation.Web]Presentation.Web.DropdownProfile -[Presentation.Web]Presentation.Web.FilterConfig -[Presentation.Web]Presentation.Web.Infrastructure.NinjectDependencyResolver -[Presentation.Web]Presentation.Web.Infrastructure.NinjectDependencyScope -[Presentation.Web]Presentation.Web.Infrastructure.UserRepositoryFactory -[Presentation.Web]Presentation.Web.Infrastructure.ProviderInitializationHttpModule -[Presentation.Web]Presentation.Web.MappingProfile -[Presentation.Web]Presentation.Web.MappingConfig -[Presentation.Web]Presentation.Web.Models* -[Presentation.Web]Presentation.Web.MvcApplication -[Presentation.Web]Presentation.Web.Properties.Settings -[Presentation.Web]Presentation.Web.RouteConfig -[Presentation.Web]Presentation.Web.Startup -[Presentation.Web]Presentation.Web.WebApiConfig
  ESLINT_DIR: Presentation.Web\Scripts\app
  TSLINT_DIR: Presentation.Web\Scripts\app
  NODEJS_VERSION: "4"
services:
- iis
- mssql2014
cache:
  - node_modules -> package.json
  - bower_components -> bower.json
configuration:
  - Debug
install:
  - ps: install-Product node $env:NODEJS_VERSION
  - npm install
before_build:
  - nuget restore %APPVEYOR_BUILD_FOLDER%\KITOS.sln -verbosity quiet
  - node_modules\.bin\gulp deploy-prod
build:
  project: KITOS.sln
  verbosity: quiet
  publish_wap: true
test_script:
  # Run frontend unit tests and coverage
  #- node_modules\.bin\gulp unit
  # Run backend unit tests and coverage
  - run-coverage.bat
before_deploy:
  - ps: .\InstallSelfSignedCert.ps1
deploy:
- provider: Local
  Presentation.Web.deploy_website: true
  Presentation.Web.site_name: Kitos
  Presentation.Web.hostname: localhost
  Presentation.Web.port: 44300
  Presentation.Web.protocol: https
  Presentation.Web.certificate: localhost
  Presentation.Web.remove_files: true
after_deploy:
  #- node_modules\.bin\gulp e2e:local
on_success:
  # Post coverage reports to Codecov.io
  - node_modules\.bin\gulp codecov
artifacts:
- path: coverage
  name: Coverage results
- path: results-protractor.json
  name: Protractor test results
- path: npm-debug.log
  name: npm error log
