version: '2.2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASSWORD}
    networks:
      - app_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    image: strongminds/kitos-pubsub:${IMAGE_TAG}
    container_name: kitos-pubsub
    depends_on:
      - rabbitmq
    volumes:
      - /etc/ssl/certs/kitos-pubsub.pfx:/etc/ssl/certs/kitos-pubsub.pfx:ro 
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      RABBIT_MQ_USER: ${RABBIT_MQ_USER}
      RABBIT_MQ_PASSWORD: ${RABBIT_MQ_PASSWORD}
      PUBSUB_API_KEY: ${PUBSUB_API_KEY}
      CERT_PASSWORD: ${CERT_PASSWORD}
      ConnectionStrings__DefaultConnection: ${PUBSUB_CONNECTION_STRING}
    ports:
      - "443:443"
    networks:
      - app_network
    extra_hosts:
       - ${IDP_HOST_MAPPING}

networks:
  app_network:
    driver: bridge

volumes:
  rabbitmq_data:    
    